### ISSUE TITLE
Please Specify "Root"

### ISSUE THREAD

**Issue by twofingerrightclick** [mudlabs/simple-diff#2]
This tool appears to do a Head~1 Head git diff yes? I am very confused what the path should be. I am trying to use it in a git hub workflow but cannot figure out what "Root" means in path` Specifies a path from root to the file or folder you want to check. ` This action runs on the machine yes? Is the root github.workspace (the repo directory)? I've tried absolute paths as well. Sorry if my confusion is from my inexperience with github workflow actions. 

`None of the files in this commits diff tree match the provided file (./folder/file.ext)`

What is the path format that it wants relative to the checked out repo? Like I would like it look at file.txt: `/home/runner/work/repoName/repoName/file.txt` on a github machine

**Comment by mudlabs** [comment]
@twofingerrightclick If your directory structure looks like this
```txt
root
| folder/file.ext
| README.md
```

You would specify the _path_ as `path: folder/file.ext`

Also, did you checkout your repo before calling this action?
- `uses: actions/checkout@v2` 

---

There's a _test_ workflow on this repository that runs on any push event. It passes this repositories `README.md` file into path. Take a look, it should help clarify how to use path.
- https://github.com/mudlabs/simple-diff/blob/master/.github/workflows/test.yaml

**Comment by mudlabs** [comment]
@twofingerrightclick I found an error in `v1.0.0` where `strict` was not being implemented as intended. Please update your use to `v1.0.1`

Also from my tests, passing the _path_ as  `./folder/file.ext` or `folder/file.ext` both seem to work.

**Comment by twofingerrightclick** [comment]
Thank you for the reply and suggestions! I am still stuck though.
Here is my workflow: 
`steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.ref }} #I even tried adding this argument like in the example test yml
    - name: Simple Diff
      uses: mudlabs/simple-diff@v1.0.1
      id: diff
      with:
    # The path of the file or folder to find in the commits diff tree.
        path: README.md
    - run: |
          echo "${{ steps.diff.outputs.added }}"
          echo "${{ steps.diff.outputs.modified }}"
          echo "${{ steps.diff.outputs.removed }}"
          echo "${{ steps.diff.outputs.renamed }}"
          echo "${{ steps.diff.outputs.name }}"  
    - name: check if xml modified `

So but it reports that it can't find the README :( And fails in strict mode =true.
`None of the files in this commits diff tree match the provided file (README.md).`

**Comment by mudlabs** [comment]
Just to be clear;
 1. You commit a change to `README.md`
 2. The workflow is triggered.
 3. Simple Diff fails with, could not find `README.md`

**Comment by twofingerrightclick** [comment]
*facepalm*
I now understand why it says diff tree. Meaning that file was not changed. Thank you for your patience. May you have no bugs in your code for the coming week.

**Comment by twofingerrightclick** [comment]
But I have discovered that the main issue also throwing me off is that it won't work with the filename `Guidelines(8th Edition).xml`. I can modify any other file in the directory, and have the action correctly detect the change in the diff tree. I think it is the parenthesis? Try running the action with a path like `File(9th Test).xml` and see what happens...

**Comment by mudlabs** [comment]
It wasn't the parenthesis, it was the space.

The action takes your `path` and tests it against the `contents_url` property of every file object in the diff tree. So it was looking for URL that contained `contents/Guidelines(8th Edition).xml`, but the `contents_url` would look like `contents/Guidelines(8th%20Edition).xml`

I've updated the code to first decode the `contents_url` using JavaScripts `decodeURIComponent`. The issue should now be resolved.

The new release is `v1.0.2`

**Comment by twofingerrightclick** [comment]
I discovered that if I remove the space it works. So `Test-9th File.md` doesn't work but Test-9thFile.md does.

**Comment by twofingerrightclick** [comment]
> It wasn't the parenthesis, it was the space.
> 
> The action takes your `path` and tests it against the `contents_url` property of every file object in the diff tree. So it was looking for URL that contained `contents/Guidelines(8th Edition).xml`, but the `contents_url` would look like `contents/Guidelines(8th%20Edition).xml`
> 
> I've updated the code to first decode the `contents_url` using JavaScripts `decodeURIComponent`. The issue should now be resolved.
> 
> The new release is `v1.0.2`

Nice work! Thanks!

**Comment by mudlabs** [comment]
Also, the `output` will now always return values. So if you set `strict` to `false` you could still inspect the actions output, if you needed to for some reason.

**Comment by twofingerrightclick** [comment]
Also `if: steps.diff.outputs.modified` always resulted in the condition evaluating as true (even if the value was false) after the update to 1.0.2. I had to specify `if: steps.diff.outputs.modified == true` in order for it to correctly evaluate. I may be wrong here, but double check that your examples in the readme evaluate correctly now with 1.0.2. I was reading [github workflow syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#operators) to figure out why...

**Comment by mudlabs** [comment]
Thanks @twofingerrightclick I've updated the README to reflect this.
